query getCurrentUser {
  authenticatedItem {
    ... on User {
      email
      id
      name
      cart {
        quantity
        id
        product {
          id
          price
          shortDescription
          title
        }
      }
      orders {
        charge
        id
        itemsCount
        total
        items {
          id
          quantity
          product {
            id
            price
            title
            shortDescription
          }
        }
      }
    }
  }
}
