query getCurrentUser {
  authenticatedItem {
    ... on User {
      email
      id
      name
      stripeId
      cart {
        quantity
        id
        product {
          id
          price
          shortDescription
          title
        }
        user {
          id
        }
      }
      orders {
        charge
        id
        itemsCount
        total
        date
        items {
          id
          quantity
          product {
            id
            price
            title
            shortDescription
          }
        }
      }
      ordersCount
      cartCount
      products {
        id
        price
        shortDescription
        title
        tags {
          name
          id
        }
      }
    }
  }
}
