query getProducts {
  products {
    id
    title
    tagsCount
    image {
      altText
      id
      image {
        url
        id
        extension
        height
        width
      }
    }
    tags {
      id
      name
    }
    author {
      name
      email
      id
    }
    content {
      document
    }
    price
    shortDescription
  }
}
